### ISSUE TITLE
Unable to build from source with flutter 2.10.4

### ISSUE THREAD

**Issue by timosturm** [vauvenal5/yaga#153]
I am strongly interested in building a nextcloud app in flutter that makes improvements over the official app. This is how I found your project. Sadly I am not able to build it myself from the `dev` branch. I am running into several problems concerning out of data dependencies and android build targets.

Nevertheless, I was able to 'fix' those issues. What I cannot fix are unhandled exceptions that occur during the app start:
```dart
E/flutter (10366): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (10366): #0      ForegroundWorker.init (package:yaga/utils/forground_worker/foreground_worker.dart:69:70)
E/flutter (10366): <asynchronous suspension>
E/flutter (10366): 
E/flutter (10366): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (10366): #0      ForegroundWorker.init (package:yaga/utils/forground_worker/foreground_worker.dart:69:70)
E/flutter (10366): <asynchronous suspension>
E/flutter (10366): 
E/flutter (10366): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (10366): #0      ForegroundWorker.init (package:yaga/utils/forground_worker/foreground_worker.dart:69:70)
E/flutter (10366): <asynchronous suspension>
E/flutter (10366): 
E/flutter (10366): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (10366): #0      ForegroundWorker.init (package:yaga/utils/forground_worker/foreground_worker.dart:69:70)
E/flutter (10366): <asynchronous suspension>
```

The output sadly does not contain any information about the origin of this method calls.
All changes I made can be seen [here](https://github.com/timosturm/yaga/pull/1/files).

**Comment by vauvenal5** [comment]
Sorry for the late response, however, I am quite occupied at work currently. I hope I can have a look into your issue during July.
